apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    name: minikube
    namespace: default
  source:
    repoURL: https://github.com/ojp2/gitops-argocd.git
    targetRevision: HEAD
    path: <PATH_TO_HELM_CHART_DIRECTORY>
    helm:
      valueFiles:
        - <PATH_TO_VALUES.YAML>
